# Generated by Django 3.2.3 on 2021-05-24 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0002_alter_communaute_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'priorite',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='communaute',
            name='nom',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('evenementiel', models.BooleanField()),
                ('date_evenement', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.communaute')),
                ('priorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.priorite')),
            ],
            options={
                'verbose_name': 'post',
                'ordering': ['titre'],
            },
        ),
    ]
